### ISSUE TITLE
Not's Warlock WA's not loading in raid

### ISSUE THREAD

**Issue by megafang** [NotWarlock/Demonology#109]
Hey Not, some of the WAs that I downloaded off of your wago do not load inside of any raid instance. For example WAs like the dot timers and PS timer and CD work everywhere but others like the pandemic markers, Main BG-AFF and contagion tracker do not show up if im in raid. The only load conditions on them are in combat, and class/talent spec. I have even tried setting the load condition to show all the time and it still will not load even though WAs says it is.

**Comment by NotWarlock** [comment]
Update your Weak Auras addon, delete all instances of the auras -- reload UI -- import -- reload UI.
