### ISSUE TITLE
Aff Rotation page missing a word

### ISSUE THREAD

**Issue by kaernunnos** [NotWarlock/Demonology#110]
Sentence at the top of the page starts "I'd like to note upfront that any cooldowns (PS/SH/etc) on cooldown". Seems to be missing the word "use"

**Comment by nasirabtw** [comment]
Resolved in 63760bbdd3a81268a87f7a123e0c23d607f733fe.

**Comment by nasirabtw** [comment]
Sorry it took so long to fix.
