### ISSUE TITLE
Itemlevel Trinket Calculator

### ISSUE THREAD

**Issue by Nazrogan** [NotWarlock/Demonology#123]
Hey Guys.
First: Thank you for this amazing source of information for Warlocks, this is so fuckin genius!
Regarding the trinket calculator for affliction, i found that there are itemlevel missing, f.e. for the Tarnished Sentinel Medallion theres no 920 , just 915 and the 925. Can you please fix this? Or is it intended?
And then I have a small request. Please write out the names of the trinkets, f.e. the "Sheath of Asara" is just named "Sheat" in the trinket list. Its pretty hard to find special trinkets, at least for us german guys, who are not so conform with the trinket shortcuts.
Anyway, go ahead, LOSS ftw ;)
Greetings,
Modulok

**Comment by NotWarlock** [comment]
Absolutely a great suggestion!
Having it taken a look at and should be fixed soon(tm).

Sorry for not seeing this sooner!
