### ISSUE TITLE
Destruction Guide needs to be updated to match patch notes!

### ISSUE THREAD

**Issue by Dertuh** [NotWarlock/Demonology#75]
http://lockonestopshop.com/#/Destruction/Introduction
http://www.wowhead.com/news=265638/world-of-warcraft-official-7-2-5-patch-notes
Some of the talents covered in the guide are out-dated as well as some of the ability changes
Reverse Entropy, Soul Conduit etc. just go over them 1 by 1 and check because I'd have to list too many things ^^ but good job! it looks amazing ty all for your contribution much love <3

**Comment by NotWarlock** [comment]
updated most of them, i think.

i might be blind tho
