### ISSUE TITLE
Feature Request: Have discussion thread be specific to subpages

### ISSUE THREAD

**Issue by jbhat** [NotWarlock/Demonology#76]
It seems like the discussion section is site-wide at the moment. I think it would be less confusing and more useful if each section, or even better each sub-page had it's own discussion. Thanks!

**Comment by NotWarlock** [comment]
Yeah, we thought we had it set to subpages but apparently the code discus told us to use was wrong :|

**Comment by jbhat** [comment]
My guess is it's based on the fact that all the pages are in fact the same "page" just different sections. At least that's my understanding of pages that use /#/ style URLs. My front-end isn't super strong though so I could be wrong.

**Comment by jbhat** [comment]
Maybe my comment was misleading. I didn't mean that the issue has to do with the URL in an of itself. But notice that when navigating to different sections of the page, the page doesn't actually reload. The content is just modified with AJAX it seems. Perhaps you can add some sort of call to Disqus in the AJAX callback to change to a different discussion thread? It probably is not straightforward, but perhaps they have documentation about how to handle this style of website.

**Comment by sergiomasellis** [comment]
@jbhat I totally understand what you mean. I've looked into it but DISQUS.reset which should switch topics based on specs isn't working as intended. I might just need to submit a ticket to their team to learn more.

**Comment by NotWarlock** [comment]
closed - discus was removed
