### ISSUE TITLE
Potential Addition - Green Fire

### ISSUE THREAD

**Issue by Hopesedge** [NotWarlock/Demonology#78]
As a One Stop Shop for Warlocks I figured the only real thing that's unique to warlocks is the Green Fire, there is also the Mage Tower which could be a helpful resource. Just figured they'd be useful for new warlocks who may want to use your site as their only resource.

**Comment by NotWarlock** [comment]
To be honest, finding a relevant video or resources that goes over getting Green Fire is going to be difficult. Finding videos/guides for Mage Tower on the other hand would not be that bad.
Gonna think about best implementation for them.
