### ISSUE TITLE
Firefox Talents page js bug

### ISSUE THREAD

**Issue by Gabb1995** [NotWarlock/Demonology#89]
Getting this error in console:
TypeError: document.registerElement is not a function

Firefox 53.0.3 (64-bit):
![Screenshot of what happens in firefox](https://user-images.githubusercontent.com/20728259/27087506-7d035faa-5055-11e7-9b4e-f15daece6e88.png)

Chromium:
![screenshot from 2017-06-13 16-30-54](https://user-images.githubusercontent.com/20728259/27087601-b3f17268-5055-11e7-8962-13e5f980f83f.png)

Quick google shows that this function is deprecated https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement

**Comment by sergiomasellis** [comment]
@Gabb1995 Thank you for posting this I'll take a look at alternative ways of using custom elements.
