### ISSUE TITLE
Hotlink to sims is wrong under gearing

### ISSUE THREAD

**Issue by ghost** [NotWarlock/Demonology#90]
It hotlinks to http://lockonestopshop.com/Destruction/Sims/Trinket
When it should link to http://lockonestopshop.com/#!/Destruction/Sims/Trinket

could be the same for the other specs also

**Comment by Gabb1995** [comment]
Can't replicate this, what browser are you using?

Steps are going to Destruction > Gearing, then clicking Sims > Trinket correct?

**Comment by sergiomasellis** [comment]
I think @izzy420 means when on a gearing page the guide links aren't updated to new url. Admittedly I am playing with the url a bit thinking of rewriting the router to use push state. (aka. no #! or # in the urls)

**Comment by NotWarlock** [comment]
fixed, links should work fine now
