### ISSUE TITLE
Menu navigation anchors tags missing hrefs

### ISSUE THREAD

**Issue by null-d3v** [NotWarlock/Demonology#91]
Menu navigation anchor tags operate with click events and have an href of the base route, #.

This prohibits a few important behaviors expected with anchor tags, such as being able to copy the href via mouse2, or opening the page in a new tab with mouse3.

For example, if I select a menu item with mouse3, a new tab opens to the base route of the site instead of the expected route represented by the menu item.

**Comment by null-d3v** [comment]
Just noticed this is fixed from my comment last night on the reddit post, nice!

**Comment by sergiomasellis** [comment]
;)

**Comment by sergiomasellis** [comment]
There are still some bugs like you can't use your browsers back and foward keys. I didn't get to it before launch but I should be able to keep improving as daily

Thanks for this report though!
