### ISSUE TITLE
Destro Rotation Page Styling Tweak

### ISSUE THREAD

**Issue by rgsmith1980** [NotWarlock/Demonology#95]
On the Destruction Warlock Rotation page, "Opener w. Backdraft" should be formatted in the same header style as "Opener w. Roaring Blaze"

http://lockonestopshop.com/#!/Destruction/Rotation

<img width="629" alt="screenshot 2017-06-13 10 58 38" src="https://user-images.githubusercontent.com/847249/27091937-479e2756-5027-11e7-80ea-2935af617c73.png">

**Comment by sergiomasellis** [comment]
Nice catch! Should be fixed now.
