### ISSUE TITLE
WoWDB Tooltips not working when DISQUS is blocked

### ISSUE THREAD

**Issue by abraemer** [NotWarlock/Demonology#97]
I noticed that when DISQUS is blocked (by Ghostery f. e.) as soon as you change the page the Tooltips from WoWDB won't load anymore. This is because on line 204 in loss.js execution of loadContent is aborted, because the global variable DISQUS is never defined (loading of DISQUS blocked by Ghostery). Because of this resetWowDB() a bit further down is never called and so the tooltips don't work.

The only change necessary would probably be to change line 203 from 
`}else{` to `}else if (typeof DISQUS !== "undefined"){`

I think there are other browser addons out there doing similar things and this would be a neat little quality of life. Especially when the fix is so small.

Awesome site. Keep up the good work.

**Comment by sergiomasellis** [comment]
Thanks for reporting this I will give this a shot.
